# Generated by Django 2.0.2 on 2018-02-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darkroom_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightsensordata',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
