# Generated by Django 2.0.2 on 2018-02-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darkroom_app', '0003_auto_20180226_1643'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LightSensorData',
            new_name='SensorData',
        ),
    ]
